-------------------------------------------------------------------------------
Test set: dao.Sql2oUserDaoTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.483 sec <<< FAILURE! - in dao.Sql2oUserDaoTest
dao.Sql2oUserDaoTest  Time elapsed: 0.483 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "102.167.175.119", user "ytpzfcwlsbzvvr", database "dh8km5l2do2ib", SSL off
	at dao.Sql2oUserDaoTest.setUp(Sql2oUserDaoTest.java:21)
Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "102.167.175.119", user "ytpzfcwlsbzvvr", database "dh8km5l2do2ib", SSL off
	at dao.Sql2oUserDaoTest.setUp(Sql2oUserDaoTest.java:21)

dao.Sql2oUserDaoTest  Time elapsed: 0.483 sec  <<< ERROR!
java.lang.NullPointerException
	at dao.Sql2oUserDaoTest.shutDown(Sql2oUserDaoTest.java:33)

